export const FoodDrinkData = [
    {
        id: 1,
        img: "https://i.pinimg.com/originals/51/f8/f5/51f8f53b6cab32db3810bc396c280158.jpg",
        title: "Astronomy Or Astrology",
        time: "7:36",
        views: "240k views",
        date: "4 months ago",
        username: "Food & Drink",
    },
    {
        id: 2,
        img: "https://www.fonstola.ru/images/201307/fonstola.ru_99032.jpg",
        title: "Advertising Outdoors",
        time: "2:19",
        views: "13k views",
        date: "15 days ago",
        username: "Food & Drink",
    },
    {
        id: 3,
        img: "https://sportishka.com/uploads/posts/2022-04/1650721352_61-sportishka-com-p-islandiya-krasivo-foto-72.jpg",
        title: "Radio Astronomy",
        time: "9:05",
        views: "1k views",
        date: "11 months ago",
        username: "Food & Drink",
    },
    {
        id: 4,
        img: "https://avatars.mds.yandex.net/get-pdb/27625/b29bf547-5476-47ab-8bae-d9d77c73ce8e/s1200?webp=false",
        title: "A Good Autoresponder",
        time: "3:40",
        views: "45k views",
        date: "2 months ago",
        username: "Food & Drink",
    },
    {
        id: 5,
        img: "https://www.lifefact.ru/wp-content/uploads/2020/09/grand-kanon.jpg",
        title: "Baby Monitor Technology",
        time: "1:56",
        views: "86k views",
        date: "7 days ago",
        username: "Food & Drink",
    },
    {
        id: 6,
        img: "https://w.forfun.com/fetch/a3/a3fada1f6d05602ff8bccebe7e0d96ac.jpeg",
        title: "Asteroids",
        time: "4:15",
        views: "123k views",
        date: "4 months ago",
        username: "Food & Drink",
    },
    {
        id: 7,
        img: "https://proprikol.ru/wp-content/uploads/2020/04/kartinki-vulkany-27.jpg",
        title: "Selecting The Right Hotel",
        time: "8:00",
        views: "123k views",
        date: "1 months ago",
        username: "Food & Drink",
    },
]