export const FavouriteData = [
    {
        id: 1,
        img: "https://sportishka.com/uploads/posts/2022-11/1667564038_1-sportishka-com-p-gollandiya-dostoprimechatelnosti-krasivo-1.jpg",
        title: "A Brief History Of Creation",
        time: "4:15",
        views: "80k views",
        date: "3 days ago",
        username: "Dollie Blair",
    },
    {
        id: 2,
        img: "https://otkrit-ka.ru/uploads/posts/2021-11/krasivye-foto-kartinki-kity-6.jpg",
        title: "Selecting The Right Hotel",
        time: "8:00",
        views: "123k views",
        date: "1 months ago",
        username: "Dollie Blair",
    },
    {
        id: 3,
        img: "https://sportishka.com/uploads/posts/2022-11/1667585574_37-sportishka-com-p-podnozhe-elbrusa-vkontakte-41.jpg",
        title: "Asteroids",
        time: "5:32",
        views: "43k views",
        date: "12 days ago",
        username: "Dollie Blair",
    },
    {
        id: 4,
        img: "https://vsegda-pomnim.com/uploads/posts/2022-04/1649210028_18-vsegda-pomnim-com-p-priroda-baikala-zimoi-foto-19.jpg",
        title: "Telescopes 101",
        time: "6:40",
        views: "11k views",
        date: "6 months ago",
        username: "Dollie Blair",
    },
    {
        id: 5,
        img: "https://35photo.pro/photos_main/564/2824381.jpg",
        title: "Medical Care Is Just",
        time: "1:45",
        views: "18k views",
        date: "2 days ago",
        username: "Dollie Blair",
    },
    {
        id: 6,
        img: "https://мойпляж.рф/wp-content/uploads/2011/05/plyazhi-krasnogo-morya.jpg",
        title: "Moon Gazing",
        time: "2:12",
        views: "67k views",
        date: "4 months ago",
        username: "Dollie Blair",
    },
    {
        id: 7,
        img: "https://putidorogi-nn.ru/images/stories/afrika/egipet/krasnoe_more_11.jpg",
        title: "Baby Monitor Technology",
        time: "1:56",
        views: "86k views",
        date: "7 days ago",
        username: "Dollie Blair",
    },
]